name: 3rdparty_ca_flask
channels:
  - defaults
dependencies:
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - openssl
  - pip=19.0.3=py37_0
  - python=3.7
  - setuptools=40.8.0=py37_0
  - sqlite=3.27.2
  - wheel=0.33.1=py37_0
  - pip:
    - asn1crypto==0.24.0
    - cffi==1.12.2
    - chardet==3.0.4
    - click==7.0
    - cryptography==2.6.1
    - flask==1.0.2
    - flask-login==0.4.1
    - idna==2.8
    - itsdangerous==1.1.0
    - jinja2==2.10
    - markupsafe==1.1.1
    - pgpy==0.4.3
    - pyasn1==0.4.5
    - pycparser==2.19
    - requests==2.21.0
    - singledispatch==3.4.0.3
    - six==1.12.0
    - urllib3==1.24.1
    - werkzeug==0.15.1
